"""
Package config - Configuration de l'application All-in-Run.
"""
from .constants import *
from .settings import settings
from .languages import (
    AVAILABLE_LANGUAGES,
    DEFAULT_LANGUAGE,
    DAYS_TRANSLATIONS,
    MONTHS_TRANSLATIONS,
    SESSION_TYPE_TRANSLATIONS,
    PHASE_TRANSLATIONS,
    UNITS_TRANSLATIONS,
    VALIDATION_ERROR_TRANSLATIONS
)

__all__ = [
    'settings',
    'AVAILABLE_LANGUAGES',
    'DEFAULT_LANGUAGE',
    'DAYS_TRANSLATIONS',
    'MONTHS_TRANSLATIONS',
    'SESSION_TYPE_TRANSLATIONS',
    'PHASE_TRANSLATIONS',
    'UNITS_TRANSLATIONS',
    'VALIDATION_ERROR_TRANSLATIONS',
    # Constants from constants.py
    'MIN_WEEKS_BEFORE_RACE',
    'MIN_TAPER_WEEKS',
    'TAPER_PHASE_RATIO',
    'DEVELOPMENT_SPECIFIC_RATIO',
    'VOLUME_REDUCTION_RACE_WEEK',
    'TAPER_FINAL_WEEK_RATIO',
    'CHARGE_DISCHARGE_PATTERN',
    'DISCHARGE_REDUCTION',
    'LONG_RUN_VOLUME_RATIO',
    'THRESHOLD_VOLUME_RATIO',
    'EF_VOLUME_RATIO',
    'WARMUP_RATIO',
    'ACTIVE_BLOCK_RATIO',
    'COOLDOWN_RATIO',
    'DEFAULT_LONG_RUN_DAY',
    'DEFAULT_THRESHOLD_DAY',
    'REST_DAY_PRIORITY',
    'DEFAULT_MIN_VOLUME',
    'DEFAULT_MAX_VOLUME',
    'DEFAULT_SESSIONS_PER_WEEK',
    'MIN_SESSIONS_PER_WEEK',
    'MAX_SESSIONS_PER_WEEK',
    'DISTANCE_PRECISION',
    'THRESHOLD_INTERVAL_MINUTES',
    'PDF_PAGE_SIZE',
    'PDF_ORIENTATION'
]